// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: uv-pb-user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nick     string `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Ctime    int32  `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetCtime() int32 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *Info) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count      int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	P          int32 `protobuf:"varint,2,opt,name=p,proto3" json:"p,omitempty"`
	N          int32 `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	TotalCount int32 `protobuf:"varint,4,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *Page) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Page) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *Page) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Page) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UserQueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32   `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string  `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Page   *Page   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	Items  []*User `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *UserQueryResult) Reset() {
	*x = UserQueryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryResult) ProtoMessage() {}

func (x *UserQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryResult.ProtoReflect.Descriptor instead.
func (*UserQueryResult) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserQueryResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *UserQueryResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *UserQueryResult) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *UserQueryResult) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserCreateTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nick     string `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserCreateTask) Reset() {
	*x = UserCreateTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCreateTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateTask) ProtoMessage() {}

func (x *UserCreateTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateTask.ProtoReflect.Descriptor instead.
func (*UserCreateTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserCreateTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserCreateTask) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserCreateTask) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserGetTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nick        string `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	AutoCreated bool   `protobuf:"varint,4,opt,name=autoCreated,proto3" json:"autoCreated,omitempty"`
}

func (x *UserGetTask) Reset() {
	*x = UserGetTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetTask) ProtoMessage() {}

func (x *UserGetTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetTask.ProtoReflect.Descriptor instead.
func (*UserGetTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserGetTask) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserGetTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGetTask) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserGetTask) GetAutoCreated() bool {
	if x != nil {
		return x.AutoCreated
	}
	return false
}

type UserSetTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string  `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name     *String `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nick     *String `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	Password *String `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserSetTask) Reset() {
	*x = UserSetTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSetTask) ProtoMessage() {}

func (x *UserSetTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSetTask.ProtoReflect.Descriptor instead.
func (*UserSetTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserSetTask) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserSetTask) GetName() *String {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserSetTask) GetNick() *String {
	if x != nil {
		return x.Nick
	}
	return nil
}

func (x *UserSetTask) GetPassword() *String {
	if x != nil {
		return x.Password
	}
	return nil
}

type UserQueryTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Q string `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	P int32  `protobuf:"varint,2,opt,name=p,proto3" json:"p,omitempty"`
	N int32  `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *UserQueryTask) Reset() {
	*x = UserQueryTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserQueryTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryTask) ProtoMessage() {}

func (x *UserQueryTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryTask.ProtoReflect.Descriptor instead.
func (*UserQueryTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserQueryTask) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *UserQueryTask) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *UserQueryTask) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type AppQueryTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Q string `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	P int32  `protobuf:"varint,2,opt,name=p,proto3" json:"p,omitempty"`
	N int32  `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *AppQueryTask) Reset() {
	*x = AppQueryTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppQueryTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppQueryTask) ProtoMessage() {}

func (x *AppQueryTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppQueryTask.ProtoReflect.Descriptor instead.
func (*AppQueryTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{9}
}

func (x *AppQueryTask) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *AppQueryTask) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *AppQueryTask) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type InfoSetTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *InfoSetTask) Reset() {
	*x = InfoSetTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoSetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoSetTask) ProtoMessage() {}

func (x *InfoSetTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoSetTask.ProtoReflect.Descriptor instead.
func (*InfoSetTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{10}
}

func (x *InfoSetTask) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *InfoSetTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InfoSetTask) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type InfoGetTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *InfoGetTask) Reset() {
	*x = InfoGetTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoGetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoGetTask) ProtoMessage() {}

func (x *InfoGetTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoGetTask.ProtoReflect.Descriptor instead.
func (*InfoGetTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{11}
}

func (x *InfoGetTask) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *InfoGetTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UserResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data   *User  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserResult) Reset() {
	*x = UserResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResult) ProtoMessage() {}

func (x *UserResult) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResult.ProtoReflect.Descriptor instead.
func (*UserResult) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *UserResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *UserResult) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type InfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data   *Info  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InfoResult) Reset() {
	*x = InfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResult) ProtoMessage() {}

func (x *InfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResult.ProtoReflect.Descriptor instead.
func (*InfoResult) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{13}
}

func (x *InfoResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *InfoResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *InfoResult) GetData() *Info {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginTask) Reset() {
	*x = LoginTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTask) ProtoMessage() {}

func (x *LoginTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTask.ProtoReflect.Descriptor instead.
func (*LoginTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{14}
}

func (x *LoginTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginTask) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{15}
}

func (x *LoginResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *LoginResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type UserBatchGetTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid []string `protobuf:"bytes,1,rep,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserBatchGetTask) Reset() {
	*x = UserBatchGetTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBatchGetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBatchGetTask) ProtoMessage() {}

func (x *UserBatchGetTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBatchGetTask.ProtoReflect.Descriptor instead.
func (*UserBatchGetTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserBatchGetTask) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

type UserBatchGetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32   `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string  `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Items  []*User `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *UserBatchGetResult) Reset() {
	*x = UserBatchGetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBatchGetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBatchGetResult) ProtoMessage() {}

func (x *UserBatchGetResult) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBatchGetResult.ProtoReflect.Descriptor instead.
func (*UserBatchGetResult) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{17}
}

func (x *UserBatchGetResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *UserBatchGetResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *UserBatchGetResult) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

type InfoBatchGetTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid []string `protobuf:"bytes,1,rep,name=uid,proto3" json:"uid,omitempty"`
	Key string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *InfoBatchGetTask) Reset() {
	*x = InfoBatchGetTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoBatchGetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoBatchGetTask) ProtoMessage() {}

func (x *InfoBatchGetTask) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoBatchGetTask.ProtoReflect.Descriptor instead.
func (*InfoBatchGetTask) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{18}
}

func (x *InfoBatchGetTask) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *InfoBatchGetTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type InfoBatchGetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32   `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string  `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Items  []*Info `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *InfoBatchGetResult) Reset() {
	*x = InfoBatchGetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uv_pb_user_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoBatchGetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoBatchGetResult) ProtoMessage() {}

func (x *InfoBatchGetResult) ProtoReflect() protoreflect.Message {
	mi := &file_uv_pb_user_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoBatchGetResult.ProtoReflect.Descriptor instead.
func (*InfoBatchGetResult) Descriptor() ([]byte, []int) {
	return file_uv_pb_user_proto_rawDescGZIP(), []int{19}
}

func (x *InfoBatchGetResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *InfoBatchGetResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *InfoBatchGetResult) GetItems() []*Info {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_uv_pb_user_proto protoreflect.FileDescriptor

var file_uv_pb_user_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x76, 0x2d, 0x70, 0x62, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x70, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x58, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x81, 0x01, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x54, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x69, 0x0a, 0x0b, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x69, 0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x6e, 0x69, 0x63,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x28, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x39, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e,
	0x22, 0x38, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x0c, 0x0a, 0x01, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x71, 0x12, 0x0c,
	0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e, 0x22, 0x45, 0x0a, 0x0b, 0x49, 0x6e,
	0x66, 0x6f, 0x53, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x5a, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x5a, 0x0a, 0x0a, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b, 0x0a, 0x09,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3b, 0x0a, 0x0b, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x24, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x12,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x12, 0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x36, 0x0a, 0x10, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x64, 0x0a, 0x12, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x20,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x32, 0xe9, 0x03, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0a,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x12, 0x11, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x54, 0x61, 0x73, 0x6b, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x49,
	0x6e, 0x66, 0x6f, 0x53, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x53, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x49,
	0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x40, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x40, 0x0a, 0x0c, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uv_pb_user_proto_rawDescOnce sync.Once
	file_uv_pb_user_proto_rawDescData = file_uv_pb_user_proto_rawDesc
)

func file_uv_pb_user_proto_rawDescGZIP() []byte {
	file_uv_pb_user_proto_rawDescOnce.Do(func() {
		file_uv_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_uv_pb_user_proto_rawDescData)
	})
	return file_uv_pb_user_proto_rawDescData
}

var file_uv_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_uv_pb_user_proto_goTypes = []interface{}{
	(*User)(nil),               // 0: user.User
	(*Info)(nil),               // 1: user.Info
	(*String)(nil),             // 2: user.String
	(*Page)(nil),               // 3: user.Page
	(*UserQueryResult)(nil),    // 4: user.UserQueryResult
	(*UserCreateTask)(nil),     // 5: user.UserCreateTask
	(*UserGetTask)(nil),        // 6: user.UserGetTask
	(*UserSetTask)(nil),        // 7: user.UserSetTask
	(*UserQueryTask)(nil),      // 8: user.UserQueryTask
	(*AppQueryTask)(nil),       // 9: user.AppQueryTask
	(*InfoSetTask)(nil),        // 10: user.InfoSetTask
	(*InfoGetTask)(nil),        // 11: user.InfoGetTask
	(*UserResult)(nil),         // 12: user.UserResult
	(*InfoResult)(nil),         // 13: user.InfoResult
	(*LoginTask)(nil),          // 14: user.LoginTask
	(*LoginResult)(nil),        // 15: user.LoginResult
	(*UserBatchGetTask)(nil),   // 16: user.UserBatchGetTask
	(*UserBatchGetResult)(nil), // 17: user.UserBatchGetResult
	(*InfoBatchGetTask)(nil),   // 18: user.InfoBatchGetTask
	(*InfoBatchGetResult)(nil), // 19: user.InfoBatchGetResult
}
var file_uv_pb_user_proto_depIdxs = []int32{
	3,  // 0: user.UserQueryResult.page:type_name -> user.Page
	0,  // 1: user.UserQueryResult.items:type_name -> user.User
	2,  // 2: user.UserSetTask.name:type_name -> user.String
	2,  // 3: user.UserSetTask.nick:type_name -> user.String
	2,  // 4: user.UserSetTask.password:type_name -> user.String
	0,  // 5: user.UserResult.data:type_name -> user.User
	1,  // 6: user.InfoResult.data:type_name -> user.Info
	0,  // 7: user.UserBatchGetResult.items:type_name -> user.User
	1,  // 8: user.InfoBatchGetResult.items:type_name -> user.Info
	5,  // 9: user.Service.UserCreate:input_type -> user.UserCreateTask
	7,  // 10: user.Service.UserSet:input_type -> user.UserSetTask
	6,  // 11: user.Service.UserGet:input_type -> user.UserGetTask
	8,  // 12: user.Service.UserQuery:input_type -> user.UserQueryTask
	10, // 13: user.Service.InfoSet:input_type -> user.InfoSetTask
	11, // 14: user.Service.InfoGet:input_type -> user.InfoGetTask
	14, // 15: user.Service.Login:input_type -> user.LoginTask
	16, // 16: user.Service.UserBatchGet:input_type -> user.UserBatchGetTask
	18, // 17: user.Service.InfoBatchGet:input_type -> user.InfoBatchGetTask
	12, // 18: user.Service.UserCreate:output_type -> user.UserResult
	12, // 19: user.Service.UserSet:output_type -> user.UserResult
	12, // 20: user.Service.UserGet:output_type -> user.UserResult
	4,  // 21: user.Service.UserQuery:output_type -> user.UserQueryResult
	13, // 22: user.Service.InfoSet:output_type -> user.InfoResult
	13, // 23: user.Service.InfoGet:output_type -> user.InfoResult
	15, // 24: user.Service.Login:output_type -> user.LoginResult
	17, // 25: user.Service.UserBatchGet:output_type -> user.UserBatchGetResult
	19, // 26: user.Service.InfoBatchGet:output_type -> user.InfoBatchGetResult
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_uv_pb_user_proto_init() }
func file_uv_pb_user_proto_init() {
	if File_uv_pb_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uv_pb_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserQueryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCreateTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSetTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserQueryTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppQueryTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoSetTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoGetTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBatchGetTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBatchGetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoBatchGetTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uv_pb_user_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoBatchGetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uv_pb_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uv_pb_user_proto_goTypes,
		DependencyIndexes: file_uv_pb_user_proto_depIdxs,
		MessageInfos:      file_uv_pb_user_proto_msgTypes,
	}.Build()
	File_uv_pb_user_proto = out.File
	file_uv_pb_user_proto_rawDesc = nil
	file_uv_pb_user_proto_goTypes = nil
	file_uv_pb_user_proto_depIdxs = nil
}
